config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show] do
    member do
      post :show_scaled
    end
  end

  # revise_auth
  scope module: :revise_auth do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  authenticated do
    namespace :admin do
      resources :cocktails, except: [:index, :show]
      resources :garnishes, except: :show
      resources :ingredients, except: :show
      resources :units, except: :show
      resources :ingredient_categories, except: :show
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :recipe_items, inverse_of: :unit, dependent: :delete_all

  validates_length_of :name, within: 1..40, allow_blank: false
  validates_length_of :abbreviation, within: 1..4, allow_blank: false
  validates_numericality_of :size_in_ounces, greater_than: 0, allow_nil: false

  default_scope lambda{ order('size_in_ounces DESC') }

  scope :named, lambda {|n|
    where('LOWER(name) like :n OR LOWER(abbreviation) LIKE :n', n: "%#{n.to_s.singularize.downcase}%")}

  def <=>(other)
    self.size_in_ounces <=> other.size_in_ounces
  end

  def abbreviation_for_amount(amount)
    return abbreviation unless name == abbreviation
    amount == 1 ? abbreviation : abbreviation.pluralize
  end

  # =============
  # Import/export
  # =============

  def self.import_from_hash(hsh)
    unit = find_or_initialize_by(hsh.slice(:name))
    unit.update(hsh)
    unit
  end

  def to_hash
    {
      name: name,
      abbreviation: abbreviation,
      size_in_ounces: size_in_ounces
    }
  end
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < ApplicationController
  # GET /units
  # GET /units.xml
  def index
    @units = Unit.all

    if @units.blank?
      redirect_to new_admin_unit_path, notice: 'No measuring units were found. Create the first one now!'
    end
  end

  # GET /units/new
  # GET /units/new.xml
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.xml
  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to admin_units_path, notice: 'Unit was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PUT /units/1
  # PUT /units/1.xml
  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to admin_units_path, notice: 'Unit was updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /units/1
  # DELETE /units/1.xml
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to admin_units_url, notice: "#{@unit.name.capitalize} unit has been deleted"
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :abbreviation, :size_in_ounces)
  end
end

app/helpers/units_helper.rb
module UnitsHelper
  def unit_to_fraction(unit)
    unit.size_in_ounces.to_f.rationalize.to_s
  end
end

app/views/admin/units/_form.html.haml
= f.input :name
= f.input :abbreviation
= f.input :size_in_ounces, min: 0, required: true

app/views/admin/units/edit.html.haml
- page_title "Edit the #{@unit.name}"

= simple_form_for(@unit, url: admin_unit_path(@unit)) do |f|
  = render 'form', f: f
  = f.submit 'Save your changes'

app/views/admin/units/index.html.haml
- page_title 'Units of measurement'

%table
  %thead
    %tr
      %th Name
      %th Abbrev
      %th Size in ounces
      %th
  %tbody
    - @units.each do |unit|
      %tr
        %td= unit.name
        %td= unit.abbreviation
        %td= html_fractions(unit_to_fraction(unit))
        %td.actions
          = link_to Icon.new(:edit), edit_admin_unit_path(unit)
          = link_to Icon.new(:trash), admin_unit_path(unit), data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}, :'aria-hidden' => true

- content_for :secondary_content do
  %p= link_to "#{Icon.new(:add)} Add a new unit".html_safe, new_admin_unit_path, class: 'call_to_action'

app/views/admin/units/new.html.haml
- page_title 'Add a unit'

= simple_form_for(@unit, url: admin_units_path) do |f|
  = render 'form', f: f
  = f.submit 'Create new unit of measurement'