config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show] do
    member do
      post :show_scaled
    end
  end

  # revise_auth
  scope module: :revise_auth do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  authenticated do
    namespace :admin do
      resources :cocktails, except: [:index, :show]
      resources :garnishes, except: :show
      resources :ingredients, except: :show
      resources :units, except: :show
      resources :ingredient_categories, except: :show
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ingredient_category.rb
class IngredientCategory < ActiveRecord::Base
  has_many :ingredients, inverse_of: :ingredient_category
  has_many :cocktails, through: :ingredients

  validates :name, presence: true, uniqueness: true

  default_scope lambda{ order('LOWER(name) ASC') }

  scope :named, lambda {|n| where(['LOWER(name) like ?', "%#{n.downcase}%"]) }

  def base_spirit?
    self.name == 'Base spirit'
  end

  def ==(other)
    return false unless other.is_a?(IngredientCategory)
    return self.name == other.name
  end

  def <=>(other)
    return -1 unless other.respond_to?(:downcase)
    if self.base_spirit? == other.base_spirit?
      self.name.downcase <=> other.name.downcase
    elsif self.base_spirit?
      -1
    else
      1
    end
  end

  # =============
  # Import/export
  # =============

  def self.import_from_hash(hsh)
    ingredient_category = find_or_initialize_by(hsh.slice(:name))
    ingredient_category.update(hsh)
    ingredient_category
  end

  def to_hash
    {
      name: name
    }
  end
end

app/controllers/admin/ingredient_categories_controller.rb
class Admin::IngredientCategoriesController < ApplicationController
  # GET /ingredient_categories
  def index
    @ingredient_categories = IngredientCategory.all
  end

  # GET /ingredient_categories/new
  def new
    @ingredient_category = IngredientCategory.new
  end

  # GET /ingredient_categories/1/edit
  def edit
    @ingredient_category = IngredientCategory.find(params[:id])
  end

  # POST /ingredient_categories
  def create
    @ingredient_category = IngredientCategory.new(ingredient_category_params)

    if @ingredient_category.save
      redirect_to admin_ingredient_categories_path, notice: 'Category was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ingredient_categories/1
  def update
    @ingredient_category = IngredientCategory.find(params[:id])
    if @ingredient_category.update(ingredient_category_params)
      redirect_to admin_ingredient_categories_path, notice: "Category was updated to #{@ingredient_category.name}."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ingredient_categories/1
  def destroy
    @ingredient_category = IngredientCategory.find(params[:id])
    @ingredient_category.destroy
    redirect_to admin_ingredient_categories_path, notice: "#{@ingredient_category.name} category has been deleted"
  end

  # Only allow a trusted parameter "white list" through.
  private def ingredient_category_params
    params.require(:ingredient_category).permit(:name)
  end
end

app/views/admin/ingredient_categories/_form.html.haml
= f.input :name, required: true

app/views/admin/ingredient_categories/edit.html.haml
- page_title "Edit #{@ingredient_category.name}"

= simple_form_for(@ingredient_category, url: admin_ingredient_category_path(@ingredient_category)) do |f|
  = render 'form', f: f
  = f.submit 'Save your changes'

app/views/admin/ingredient_categories/index.html.haml
- page_title 'Ingredient Categories'

%table
  %thead
    %tr
      %th Name
      %th
  %tbody
    - @ingredient_categories.each do |ingredient_category|
      %tr
        %td= ingredient_category.name
        %td.actions
          = link_to Icon.new(:edit), edit_admin_ingredient_category_path(ingredient_category)
          = link_to Icon.new(:trash), admin_ingredient_category_path(ingredient_category), data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}, :'aria-hidden' => true

- content_for :secondary_content do
  %p= link_to "#{Icon.new(:add)} Add a category".html_safe, new_admin_ingredient_category_path, class: 'call_to_action'

app/views/admin/ingredient_categories/new.html.haml
- page_title 'New ingredient category'

= simple_form_for(@ingredient_category, url: admin_ingredient_categories_path) do |f|
  = render 'form', f: f
  = f.submit 'Create a new category'