config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show] do
    member do
      post :show_scaled
    end
  end

  # revise_auth
  scope module: :revise_auth do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  authenticated do
    namespace :admin do
      resources :cocktails, except: [:index, :show]
      resources :garnishes, except: :show
      resources :ingredients, except: :show
      resources :units, except: :show
      resources :ingredient_categories, except: :show
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_items, inverse_of: :ingredient, dependent: :delete_all
  has_many :cocktails, through: :recipe_items
  belongs_to :ingredient_category, inverse_of: :ingredients

  validates_presence_of :name, :ingredient_category_id
  validates_uniqueness_of :name

  default_scope -> { order("LOWER(#{quoted_table_name}.name) ASC") }

  scope :named, ->(name) { where(["LOWER(#{quoted_table_name}.name) like ?", "%#{name.downcase}%"]) }

  def ==(other)
    return false unless other.is_a?(Ingredient)
    return self.name == other.name
  end

  def <=>(other)
    if self.ingredient_category != other.ingredient_category
      if self.ingredient_category&.base_spirit?
        -1
      elsif other.ingredient_category&.base_spirit?
        1
      else
        self.name.downcase <=> other.name.downcase
      end
    else
      self.name.downcase <=> other.name.downcase
    end
  end

  # =============
  # Import/export
  # =============

  def self.import_from_hash(hsh)
    ingredient = find_or_initialize_by(hsh.slice(:name))
    ingredient.ingredient_category = IngredientCategory.where(name: hsh.delete(:ingredient_category)).first
    ingredient.update(hsh)
    ingredient
  end

  def to_hash
    {
      name: name,
      notes: notes.present? ? notes : nil,
      ingredient_category: ingredient_category.name
    }
  end
end

app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.xml
  def index
    @ingredients = if params[:ingredient_category]
      @ingredient_category = IngredientCategory.find(params[:ingredient_category])
      @ingredient_category.ingredients.all
    else
      Ingredient.includes(:ingredient_category).all
    end

    if @ingredients.blank?
      redirect_to new_admin_ingredient_path, notice: 'No ingredients were found. Create the first one now!'
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.xml
  def new
    preload_validation_data
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
    preload_validation_data
  end

  # POST /ingredients
  # POST /ingredients.xml
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to admin_ingredients_path, notice: "#{@ingredient.name} has been added to the pantry"
    else
      preload_validation_data
      render :new, status: :unprocessable_entity
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.xml
  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      redirect_to admin_ingredients_path, notice: 'Ingredient was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.xml
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to(admin_ingredients_url, notice: "#{@ingredient.name} has been deleted")
  end

  private def ingredient_params
    params.require(:ingredient).permit(:name, :notes, :ingredient_category_id)
  end

  private def preload_validation_data
    @cocktails = @ingredient.try(:cocktails)
    @ingredient_categories = IngredientCategory.all
  end
end

app/views/admin/ingredients/_form.html.haml
= f.input :name, required: true
= f.input :ingredient_category_id, as: :select, collection: @ingredient_categories, required: true
= f.input :notes

app/views/admin/ingredients/edit.html.haml
- page_title "Edit #{@ingredient.name}"

= simple_form_for(@ingredient, url: admin_ingredient_path(@ingredient)) do |f|
  = render 'form', f: f
  = f.submit 'Save your changes'

- if @cocktails.present?
  - content_for :secondary_content do
    %h3 Cocktails with #{@ingredient.name}
    %ul
      - @cocktails.each do |cocktail|
        %li= link_to cocktail.name, cocktail

app/views/admin/ingredients/index.html.haml
- if @ingredient_category.present?
  - page_title "#{@ingredient_category.name} ingredients"
  %p= link_to "Show all ingredients", admin_ingredients_path
- else
  - page_title "Ingredients"

%table
  %thead
    %tr
      %th Name
      %th Category
      %th Notes
      %th
  %tbody
    - @ingredients.each do |ingredient|
      %tr
        %td= ingredient.name
        %td
          - if ingredient.ingredient_category.present?
            = link_to ingredient.ingredient_category.name, admin_ingredients_path(ingredient_category: ingredient.ingredient_category)
        %td= simple_format(auto_link(ingredient.notes))
        %td.actions
          = link_to Icon.new(:edit), edit_admin_ingredient_path(ingredient)
          = link_to Icon.new(:trash), admin_ingredient_path(ingredient), data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}, :'aria-hidden' => true

- content_for :secondary_content do
  %p= link_to "#{Icon.new(:add)} Add an ingredient".html_safe, new_admin_ingredient_path, class: 'call_to_action'

app/views/admin/ingredients/new.html.haml
- page_title 'New ingredient'

= simple_form_for @ingredient, url: admin_ingredients_path do |f|
  = render partial: 'form', locals: {f: f}
  = f.submit 'Create a new ingredient'