config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show] do
    member do
      post :show_scaled
    end
  end

  # revise_auth
  scope module: :revise_auth do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  authenticated do
    namespace :admin do
      resources :cocktails, except: [:index, :show]
      resources :garnishes, except: :show
      resources :ingredients, except: :show
      resources :units, except: :show
      resources :ingredient_categories, except: :show
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/garnish.rb
class Garnish < ActiveRecord::Base
  has_and_belongs_to_many :cocktails, inverse_of: :garnishes

  default_scope lambda{ order('name ASC') }

  validates_presence_of :name

  # =============
  # Import/export
  # =============

  def self.import_from_hash(hsh)
    garnish = find_or_initialize_by(hsh.slice(:name))
    garnish.update(hsh)
    garnish
  end

  def to_hash
    {
      name: name
    }
  end
end

app/controllers/admin/garnishes_controller.rb
class Admin::GarnishesController < ApplicationController
  # GET /garnishes
  def index
    @garnishes = Garnish.all
  end

  # GET /garnishes/new
  def new
    @garnish = Garnish.new
  end

  # GET /garnishes/1/edit
  def edit
    @garnish = Garnish.find(params[:id])
  end

  # POST /garnishes
  def create
    @garnish = Garnish.new(garnish_params)

    if @garnish.save
      redirect_to admin_garnishes_path, notice: 'Garnish was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /garnishes/1
  def update
    @garnish = Garnish.find(params[:id])
    if @garnish.update(garnish_params)
      redirect_to admin_garnishes_path, notice: 'Garnish was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /garnishes/1
  def destroy
    @garnish = Garnish.find(params[:id])
    @garnish.destroy
    redirect_to admin_garnishes_path, notice: "#{@garnish.name.capitalize} garnish was successfully destroyed"
  end

  # Only allow a trusted parameter "white list" through.
  private def garnish_params
    params.require(:garnish).permit(:name)
  end
end

app/views/admin/garnishes/_form.html.haml
= f.input :name

app/views/admin/garnishes/edit.html.haml
- page_title "Edit #{@garnish.name}"

= simple_form_for(@garnish, url: admin_garnish_path(@garnish)) do |f|
  = render 'form', f: f
  = f.submit 'Save your changes'

- if @cocktails.present?
  - content_for :secondary_content do
    %h3 Cocktails with #{@garnish.name}
    %ul
      - @cocktails.each do |cocktail|
        %li= link_to cocktail.name, cocktail

app/views/admin/garnishes/index.html.haml
- page_title 'Garnishes'

%table
  %thead
    %tr
      %th Name
      %th

  %tbody
    - @garnishes.each do |garnish|
      %tr
        %td= garnish.name
        %td.actions
          = link_to Icon.new(:edit), edit_admin_garnish_path(garnish)
          = link_to Icon.new(:trash), admin_garnish_path(garnish), data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}, :'aria-hidden' => true

- content_for :secondary_content do
  %p= link_to "#{Icon.new(:add)} Add a garnish".html_safe, new_admin_garnish_path, class: "call_to_action"

app/views/admin/garnishes/new.html.haml
- page_title 'New garnish'

= simple_form_for(@garnish, url: admin_garnishes_path) do |f|
  = render 'form', f: f
  = f.submit 'Create a new garnish'